### ISSUE TITLE
[Request] Dark theme (especially) for amoled devices

### ISSUE THREAD

**Issue by stmblfrcr** [iamOgunyinka/Crane#1]
Great work, something like this was really needed. Long story short - a lot of people appreciate the black theme with OLED devices or just because they like the dark. Hence, if it wouldn't be that much trouble implementing it...thanks and regards.

**Comment by iamOgunyinka** [comment]
No troubles, I'll see what I can do in the next few days.

**Comment by stmblfrcr** [comment]
Thanks a bunch!

**Comment by iamOgunyinka** [comment]
@stmblfrcr 
OK done! Next update has the OLED support now. Therefore, I'll have to close this now. Please open a new issue for another feature request.

**Comment by stmblfrcr** [comment]
Thanks again! Will certainly do :)

**Comment by iamOgunyinka** [comment]
![img_20160729_181855](https://cloud.githubusercontent.com/assets/4146085/17257216/067bdb6a-55b9-11e6-853b-7c23e24d5626.png)

Sneak peak from my Z10 :)
