### ISSUE TITLE
[Request] Background Functionality

### ISSUE THREAD

**Issue by stmblfrcr** [iamOgunyinka/Crane#2]
Wouldn't it be cool, if your app had background functionality? Especially with large downloads users might want to use their phone otherwise in the mean time. Probably not the most easy thing to implement, but greatly appreciated nonetheless.

https://developer.blackberry.com/native/documentation/device_platform/headless_apps/

**Comment by iamOgunyinka** [comment]
As much as this functionality sounds really cooool, I don't see why users can't keep a single app opened, even for large downloads. On Desktops, at least all Linux flavors and Windows machines I've used, I haven't seen a download manager( talk wget for CLI ) that runs in the background. It kind of sound creepy to me -- not knowing what on earth the said "download manager" would be doing in the background. I mean yes, it does sound nice, I just haven't seen a very strong convincing reason to implement it.

If you're on Facebook, we may discuss this and other features more, if you have the time, of course. https://facebook.com/TheRealOgunyinka
