### ISSUE TITLE
[Request] Enhance download capabilities 

### ISSUE THREAD

**Issue by stmblfrcr** [iamOgunyinka/Crane#4]
So, another one :) - how about vastly improving download capabilities by using youtube-dl https://github.com/rg3/youtube-dl . Just needs Python, which is already available. Then one could easily download from various video sites like YouTube and many others.

**Comment by iamOgunyinka** [comment]
The first version of the app added this, albeit not with youtube-dl, but it was rejected. It seems to be frowned upon by the platform( trying to avoid lawsuits or whatnot ) and the app couldn't pass the review phase. I had to remove it.
